# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 124d6b576bd96dcfc644ca78d241965721677599e2683a67537c48d5139a1a9d3ab774256c84b81919794b8ebf6fa361f8d085518a3c3af6f9273caa51c3b07c

test:
  secret_key_base: 1d4b52454e75e97245318cbab16c966ef466aa39e23f600cfd72d9638b71cec6af03938f0309eddbe34f988166baf8906b8c34750d976a2ec057a0e256242f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
